version: '3.8'
services:

  lakefs:
    image: treeverse/lakefs:latest
    container_name: lakefs
    ports:
      - 8000:8000
    environment:
      - LAKEFS_DATABASE_TYPE=local
      - LAKEFS_BLOCKSTORE_TYPE=s3
      - LAKEFS_BLOCKSTORE_S3_FORCE_PATH_STYLE=true
      - LAKEFS_BLOCKSTORE_S3_ENDPOINT=http://minio:9000
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_ACCESS_KEY_ID=${MINIO_USER}
      - LAKEFS_BLOCKSTORE_S3_CREDENTIALS_SECRET_ACCESS_KEY=${MINIO_PASSWORD}
      - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=some random secret string
      - LAKECTL_SERVER_ENDPOINT_URL=http://localhost:8000
    depends_on:
      - minio
    networks:
      - dbnetwork


  # Service for the Minio instance
  # This container runs the minio S3 buckets and console
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/mast/s3data:/mnt/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
      MINIO_VOLUMES: "/mnt/data"
    command: ['server', '/mnt/data', '--console-address', ":9001"]
    networks:
      - dbnetwork

  # This service a bucket for the mast data is none exists.
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    volumes:
     - ./data/:/data
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set srv https://minio:9000 minio99 minio123;
      /usr/bin/mc mb srv/mast;
      /usr/bin/mc anonymous set public srv/mast;
      exit 0;
      "
    networks:
      - dbnetwork

networks:
  dbnetwork:
    name: dbnetwork
    driver: bridge

volumes:
    postgres:
    pgadmin:
    acme:
    certs:
    vhost:
    html:
